"use client";

import { useMemo, useState } from "react";

function cleanText(value, fallback = "") {
  const text = String(value ?? "").trim();
  return text || fallback;
}

function buildWhatsAppStrategyMessage({ strategyData, teamName, overs }) {
  const strategy = strategyData?.strategy;
  if (!strategy) return "";

  const leagueName = cleanText(strategyData?.league?.name);
  const selectedTeamName = cleanText(strategyData?.teamName, cleanText(teamName, "Selected Team"));
  const oversPerInnings = Number(strategyData?.oversPerInnings || overs || 20);
  const battingOrder = strategy.battingOrder || [];
  const bowlingPlan = strategy.bowlingPlan || [];
  const scenarioPlan = strategy.scenarioPlan || [];
  const warnings = strategy.warnings || [];

  const lines = [
    "🏏 *Cric4All AI Match Strategy*",
    "",
  ];

  if (leagueName) {
    lines.push(`🏆 *League:* ${leagueName}`);
  }

  lines.push(
    `👥 *Team:* ${selectedTeamName}`,
    `🎯 *Format:* ${oversPerInnings} overs`,
    "",
    "━━━━━━━━━━━━━━━━━━",
    "🏏 *Batting Order*",
    ""
  );

  if (battingOrder.length) {
    battingOrder.forEach((player, index) => {
      const position = Number(player.position) || index + 1;
      const role = cleanText(player.role);
      lines.push(`${position}. ${cleanText(player.playerName, "Player")}${role ? ` — ${role}` : ""}`);
    });
  } else {
    lines.push("No batting order is available.");
  }

  lines.push("", "━━━━━━━━━━━━━━━━━━", "🎯 *Bowling Plan*", "");

  if (bowlingPlan.length) {
    bowlingPlan.forEach((item, index) => {
      const overNumber = Number(item.over) || index + 1;
      const phase = cleanText(item.phase);
      lines.push(`Over ${overNumber}: ${cleanText(item.playerName, "Bowler")}${phase ? ` (${phase})` : ""}`);
    });
  } else {
    lines.push("No historical bowling plan is available.");
  }

  if (scenarioPlan.length) {
    lines.push("", "━━━━━━━━━━━━━━━━━━", "💡 *Match Recommendations*", "");

    scenarioPlan.slice(0, 6).forEach((item) => {
      const situation = cleanText(item.situation);
      const recommendation = cleanText(item.recommendation);
      if (situation && recommendation) {
        lines.push(`• *${situation}:* ${recommendation}`);
      } else if (recommendation) {
        lines.push(`• ${recommendation}`);
      }
    });
  }

  if (warnings.length) {
    lines.push("", "━━━━━━━━━━━━━━━━━━", "⚠️ *Data Notes*", "");
    warnings.slice(0, 4).forEach((warning) => lines.push(`• ${cleanText(warning)}`));
  }

  lines.push("", "Generated by Cric4All AI", "https://cric4all.app");

  return lines.join("\n");
}

export default function AIMatchStrategyPanel({
  teamName,
  players,
  defaultOvers = 20,
  minimumPlayers = 4,
  strategyType = "GENERATED_TEAM",
}) {
  const [overs, setOvers] = useState(defaultOvers);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [shareNotice, setShareNotice] = useState("");
  const [strategyData, setStrategyData] = useState(null);
  const [activeTab, setActiveTab] = useState("BATTING");

  const playerIds = useMemo(
    () =>
      [...new Set(
        (players || [])
          .map((player) => Number(player.id ?? player.playerKey))
          .filter((id) => Number.isInteger(id) && id > 0)
      )],
    [players]
  );

  const whatsappMessage = useMemo(
    () => buildWhatsAppStrategyMessage({ strategyData, teamName, overs }),
    [strategyData, teamName, overs]
  );

  async function generate() {
    if (playerIds.length < minimumPlayers) {
      setError(`At least ${minimumPlayers} players are required.`);
      return;
    }

    setLoading(true);
    setError("");
    setShareNotice("");

    try {
      const response = await fetch("/api/ai-team-strategy/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          teamName,
          playerIds,
          oversPerInnings: Number(overs),
          strategyType,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate strategy.");
      }

      setStrategyData(data);
      setActiveTab("BATTING");
    } catch (requestError) {
      setError(requestError.message || "Failed to generate strategy.");
    } finally {
      setLoading(false);
    }
  }

  function shareToWhatsApp() {
    if (!whatsappMessage) {
      setShareNotice("Generate the match strategy before sharing it.");
      return;
    }

    setShareNotice("");

    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(whatsappMessage)}`;
    const openedWindow = window.open(whatsappUrl, "_blank", "noopener,noreferrer");

    if (!openedWindow) {
      window.location.href = whatsappUrl;
    }
  }

  const strategy = strategyData?.strategy;

  return (
    <section className="c4tb-ai-strategy">
      <header className="c4tb-ai-strategy-head">
        <div>
          <span>✨ Private beta</span>
          <h2>AI Match Strategy</h2>
          <p>
            Generate a batting order and over-by-over bowling plan from Cric4All
            ball history.
          </p>
        </div>

        <div className="c4tb-ai-strategy-team">
          <small>Selected team</small>
          <strong>{teamName}</strong>
          <span>{players.length} players</span>
        </div>
      </header>

      <div className="c4tb-ai-strategy-controls">
        <label>
          <span>Overs per innings</span>
          <input
            type="number"
            min="1"
            max="100"
            value={overs}
            onChange={(event) => setOvers(event.target.value)}
          />
        </label>

        <button
          type="button"
          onClick={generate}
          disabled={loading || playerIds.length < minimumPlayers}
        >
          {loading
            ? "Analyzing balls and statistics..."
            : "✨ Generate Match Strategy"}
        </button>
      </div>

      {error && <div className="c4tb-ai-strategy-error">{error}</div>}
      {shareNotice && <div className="c4tb-ai-strategy-share-notice">{shareNotice}</div>}

      {!strategy && !loading && (
        <div className="c4tb-ai-strategy-empty">
          <strong>Ready to analyze this team</strong>
          <p>
            Cric4All will compare player form, batting phases, bowling economy,
            wickets, dot balls, extras, and match experience.
          </p>
        </div>
      )}

      {strategy && (
        <>
          <div className="c4tb-ai-strategy-result-actions">
            <div>
              <small>Strategy ready</small>
              <strong>Share the complete plan with your team</strong>
            </div>

            <button type="button" className="c4tb-whatsapp-share-btn" onClick={shareToWhatsApp}>
              <span aria-hidden="true">📲</span>
              Share to WhatsApp
            </button>
          </div>

          <nav className="c4tb-ai-strategy-tabs">
            <button
              type="button"
              className={activeTab === "BATTING" ? "active" : ""}
              onClick={() => setActiveTab("BATTING")}
            >
              Batting Order
            </button>
            <button
              type="button"
              className={activeTab === "BOWLING" ? "active" : ""}
              onClick={() => setActiveTab("BOWLING")}
            >
              Bowling Plan
            </button>
            <button
              type="button"
              className={activeTab === "SCENARIOS" ? "active" : ""}
              onClick={() => setActiveTab("SCENARIOS")}
            >
              Match Scenarios
            </button>
          </nav>

          {activeTab === "BATTING" && (
            <div className="c4tb-strategy-list">
              {(strategy.battingOrder || []).map((player) => (
                <article key={player.playerId}>
                  <div className="c4tb-strategy-position">{player.position}</div>
                  <div>
                    <span>{player.role}</span>
                    <h3>{player.playerName}</h3>
                    <ul>
                      {(player.reasons || []).map((reason) => (
                        <li key={reason}>{reason}</li>
                      ))}
                    </ul>
                  </div>
                  <div className="c4tb-strategy-confidence">
                    <small>Confidence</small>
                    <strong>{Math.round(player.confidence || 0)}%</strong>
                  </div>
                </article>
              ))}
            </div>
          )}

          {activeTab === "BOWLING" && (
            <div className="c4tb-strategy-list">
              {(strategy.bowlingPlan || []).length ? (
                strategy.bowlingPlan.map((item) => (
                  <article key={item.over}>
                    <div className="c4tb-strategy-position">{item.over}</div>
                    <div>
                      <span>{item.phase}</span>
                      <h3>{item.playerName}</h3>
                      <ul>
                        {(item.reasons || []).map((reason) => (
                          <li key={reason}>{reason}</li>
                        ))}
                      </ul>
                    </div>
                    <div className="c4tb-strategy-confidence">
                      <small>Score</small>
                      <strong>{Math.round(item.score || 0)}</strong>
                    </div>
                  </article>
                ))
              ) : (
                <div className="c4tb-ai-strategy-empty">
                  No historical bowling data was found for these players.
                </div>
              )}
            </div>
          )}

          {activeTab === "SCENARIOS" && (
            <div className="c4tb-strategy-scenarios">
              {(strategy.scenarioPlan || []).map((item) => (
                <article key={item.situation}>
                  <span>Situation</span>
                  <h3>{item.situation}</h3>
                  <p>{item.recommendation}</p>
                </article>
              ))}
            </div>
          )}

          {!!strategy.warnings?.length && (
            <div className="c4tb-strategy-warnings">
              <strong>Data-confidence warnings</strong>
              <ul>
                {strategy.warnings.map((warning) => (
                  <li key={warning}>{warning}</li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}
    </section>
  );
}
